// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTFqxwgWrg5I1SM6-mtJKYwnMWdiZhRfg',
    appId: '1:990070634096:web:184f036aca58bc4dfa66b5',
    messagingSenderId: '990070634096',
    projectId: 'rana-todo-list',
    authDomain: 'rana-todo-list.firebaseapp.com',
    storageBucket: 'rana-todo-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GoRb0FfJ2d_g3t2vY2zezU8LvzcrCC4',
    appId: '1:990070634096:android:eab99ac5b2d7229bfa66b5',
    messagingSenderId: '990070634096',
    projectId: 'rana-todo-list',
    storageBucket: 'rana-todo-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPmcrlQ2FZfwNHXNlYPK7Mj_jFO3LcxbE',
    appId: '1:990070634096:ios:53cddc5cb767e137fa66b5',
    messagingSenderId: '990070634096',
    projectId: 'rana-todo-list',
    storageBucket: 'rana-todo-list.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPmcrlQ2FZfwNHXNlYPK7Mj_jFO3LcxbE',
    appId: '1:990070634096:ios:92ba0f2ceabd968bfa66b5',
    messagingSenderId: '990070634096',
    projectId: 'rana-todo-list',
    storageBucket: 'rana-todo-list.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
